import {
  Loader2,
  User,
  Lock,
  Mail,
  Eye,
  EyeOff,
  Github,
  Chrome,
  AlertCircle,
  CheckCircle2,
  X,
  Menu,
  X as XIcon,
  Home,
  Settings,
  LogOut,
  Bell,
  Search,
  Plus,
  Edit,
  Trash2,
  Download,
  Upload,
  RefreshCw,
  MoreHorizontal,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Star,
  Sparkles
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  user: User,
  lock: Lock,
  mail: Mail,
  eye: Eye,
  eyeOff: EyeOff,
  github: Github,
  google: Chrome,
  alert: AlertCircle,
  check: CheckCircle2,
  close: X,
  menu: Menu,
  x: XIcon,
  home: Home,
  settings: Settings,
  logout: LogOut,
  bell: Bell,
  search: Search,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  more: MoreHorizontal,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  star: Star,
  sparkles: Sparkles,
}